/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Veiw;

import Controller.OrderController;
import Controller.SuplierController;
import Model.SuplierModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sasanka
 */
public class AddSuplier extends javax.swing.JFrame {

    /**
     * Creates new form SuplierVeiw
     */
    public AddSuplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSuplierName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSuplierId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSuplierAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSuplierTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSuplierCompany = new javax.swing.JTextField();
        tblSuplierClear = new javax.swing.JButton();
        tblSuplierSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(578, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 65, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Suplier");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));

        txtSuplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuplierNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtSuplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 210, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Suplier Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Suplier ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 20));

        txtSuplierId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuplierIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtSuplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Suplier Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 20));

        txtSuplierAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuplierAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtSuplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Suplier Tel");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 20));

        txtSuplierTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuplierTelActionPerformed(evt);
            }
        });
        jPanel1.add(txtSuplierTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Suplier Company");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 20));
        jPanel1.add(txtSuplierCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 210, -1));

        tblSuplierClear.setBackground(new java.awt.Color(37, 51, 224));
        tblSuplierClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblSuplierClear.setForeground(new java.awt.Color(255, 255, 255));
        tblSuplierClear.setText("Clear");
        tblSuplierClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSuplierClearActionPerformed(evt);
            }
        });
        jPanel1.add(tblSuplierClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 100, 30));

        tblSuplierSave.setBackground(new java.awt.Color(37, 51, 224));
        tblSuplierSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblSuplierSave.setForeground(new java.awt.Color(255, 255, 255));
        tblSuplierSave.setText("Save");
        tblSuplierSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSuplierSaveActionPerformed(evt);
            }
        });
        jPanel1.add(tblSuplierSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblSuplierSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSuplierSaveActionPerformed
               SuplierModel s=new SuplierModel(txtSuplierName.getText(), txtSuplierId.getText(), txtSuplierAddress.getText(),
                txtSuplierTel.getText(), txtSuplierCompany.getText());
               
        if(isNull()){
             TblSuplier ts=null;
        try {
            ts = new TblSuplier();
        } catch (SQLException ex) {
            Logger.getLogger(AddSuplier.class.getName()).log(Level.SEVERE, null, ex);
        }

           JOptionPane.showMessageDialog(null, "Fill the all feild");
            ts.setVisible(true);
            this.setVisible(false);
            ts.setDefaultCloseOperation(3);
        return ;
        }else{
            
        try {
            if(new SuplierController().saveSuplier(s)){
                JOptionPane.showMessageDialog(null, "Success");
                new TblSuplier().updateTable();
            }else{
                JOptionPane.showMessageDialog(null, "Fail");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddSuplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        ClearTextcache();
        
        }
         TblSuplier ts=null;
        try {
            ts = new TblSuplier();
        } catch (SQLException ex) {
            Logger.getLogger(AddSuplier.class.getName()).log(Level.SEVERE, null, ex);
        }

        ts.setVisible(true);
        this.setVisible(false);
        ts.setDefaultCloseOperation(3);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSuplierSaveActionPerformed

    private void tblSuplierClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSuplierClearActionPerformed
        TblSuplier t=null;
        try {
            t = new TblSuplier();
        } catch (SQLException ex) {
            Logger.getLogger(AddSuplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
        t.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSuplierClearActionPerformed

    private void txtSuplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuplierNameActionPerformed
        txtSuplierId.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuplierNameActionPerformed

    private void txtSuplierIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuplierIdActionPerformed
        txtSuplierAddress.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuplierIdActionPerformed

    private void txtSuplierAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuplierAddressActionPerformed
        txtSuplierTel.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuplierAddressActionPerformed

    private void txtSuplierTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuplierTelActionPerformed
        txtSuplierCompany.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuplierTelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSuplier().setVisible(true);
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tblSuplierClear;
    private javax.swing.JButton tblSuplierSave;
    private javax.swing.JTextField txtSuplierAddress;
    private javax.swing.JTextField txtSuplierCompany;
    private javax.swing.JTextField txtSuplierId;
    private javax.swing.JTextField txtSuplierName;
    private javax.swing.JTextField txtSuplierTel;
    // End of variables declaration//GEN-END:variables

    private void ClearTextcache() {
      txtSuplierName.setText(null);
      txtSuplierId.setText(null);
      txtSuplierCompany.setText(null);
      txtSuplierAddress.setText(null);
      txtSuplierTel.setText(null);
    }

    private boolean isNull() {
       return txtSuplierAddress.getText().equalsIgnoreCase("")||txtSuplierCompany.getText().equalsIgnoreCase("")||
               txtSuplierId.getText().equalsIgnoreCase("")||txtSuplierName.getText().equalsIgnoreCase("")||
               txtSuplierTel.getText().equalsIgnoreCase("");
    }
}
