/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Veiw;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sasanka
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSells = new javax.swing.JButton();
        btnSetBill = new javax.swing.JButton();
        btnMedicin = new javax.swing.JButton();
        btnSuplier = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 65, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 80, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 70));

        btnSells.setBackground(new java.awt.Color(207, 207, 255));
        btnSells.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSells.setForeground(new java.awt.Color(46, 65, 80));
        btnSells.setText("Sells");
        btnSells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellsActionPerformed(evt);
            }
        });
        jPanel1.add(btnSells, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 200, 110));

        btnSetBill.setBackground(new java.awt.Color(207, 207, 255));
        btnSetBill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSetBill.setForeground(new java.awt.Color(46, 65, 80));
        btnSetBill.setText("Set Bill");
        btnSetBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnSetBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 110));

        btnMedicin.setBackground(new java.awt.Color(207, 207, 255));
        btnMedicin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMedicin.setForeground(new java.awt.Color(46, 65, 80));
        btnMedicin.setText("Medicin");
        btnMedicin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicinActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedicin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, 110));

        btnSuplier.setBackground(new java.awt.Color(207, 207, 255));
        btnSuplier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSuplier.setForeground(new java.awt.Color(46, 65, 80));
        btnSuplier.setText("Suplier");
        btnSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 200, 110));

        btnCustomer.setBackground(new java.awt.Color(207, 207, 255));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(46, 65, 80));
        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 200, 110));

        btnOrder.setBackground(new java.awt.Color(207, 207, 255));
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(46, 65, 80));
        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 200, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetBillActionPerformed
        SetBillView sb = new SetBillView();
        sb.setVisible(true);

        this.setVisible(false);
        sb.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetBillActionPerformed

    private void btnMedicinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicinActionPerformed
        try {
            TblMedicin tm = new TblMedicin();
            tm.setVisible(true);
            
            this.setVisible(false);
            tm.setDefaultCloseOperation(3);
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMedicinActionPerformed

    private void btnSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuplierActionPerformed
        try {
            TblSuplier ts = new TblSuplier();
            ts.setVisible(true);
            
            this.setVisible(false);
            ts.setDefaultCloseOperation(3);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuplierActionPerformed

    private void btnSellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellsActionPerformed
        TblSells ts=null;
        try {
            ts = new TblSells();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ts.setVisible(true);
        this.setVisible(false);
        ts.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSellsActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        try {
            TblCustomer tc = new TblCustomer();
            tc.setVisible(true);
            this.setVisible(false);
            tc.setDefaultCloseOperation(3);
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
       
        try {
         TblOrder o = new TblOrder();
        o.setVisible(true);
        this.setVisible(false);
        o.setDefaultCloseOperation(3);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnMedicin;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSells;
    private javax.swing.JButton btnSetBill;
    private javax.swing.JButton btnSuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
