/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Veiw;

import Controller.MedicinController;
import Controller.SetBillController;
import Model.MedicinModel;
import Model.SetBillModel;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.Global;

/**
 *
 * @author Sasanka
 */
public class SetBillView extends javax.swing.JFrame {
     private static double sum; 
    /**
     * Creates new form SetBillView
     */
    public SetBillView() {
       initComponents();
       setDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPationId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDoctorRegNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDoctorTel = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblbill = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddBill = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JLabel();
        txtBlance = new javax.swing.JLabel();
        DateTime = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 65, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Set Bill");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 770, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pation ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        txtPationId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPationIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Doctor Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 20));

        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Doctor Reg No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 20));

        txtDoctorRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorRegNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoctorRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Doctor Tel");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 20));

        txtDoctorTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorTelActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoctorTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 210, -1));

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 220, 30));

        tblbill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Madicin Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblbill);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 330, 180));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 80, 20));
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 60, -1));

        btnAddBill.setBackground(new java.awt.Color(37, 51, 224));
        btnAddBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddBill.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBill.setText("Add Bill");
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 100, 30));

        btnCancel.setBackground(new java.awt.Color(37, 51, 224));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 100, 30));

        jComboBox1.setBackground(new java.awt.Color(153, 255, 204));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox1KeyTyped(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 220, 30));

        btnAdd.setBackground(new java.awt.Color(37, 51, 224));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Order Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 20));

        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Blance");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Amount");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Payment");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAmount.setText("00.00");
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 20));

        txtBlance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBlance.setText("00.00");
        jPanel1.add(txtBlance, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, 20));

        DateTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(DateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 100, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Date  :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        txtPayment.setOpaque(false);
        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
         
        SetBillModel order=new SetBillModel(txtPationId.getText(), txtOrderId.getText());
        SetBillModel sell=new SetBillModel(txtOrderId.getText(), txtDoctorRegNo.getText(),
                Double.parseDouble(txtAmount.getText()), 
                Double.parseDouble(txtPayment.getText()),Double.parseDouble(txtBlance.getText()));
          ArrayList<MedicinModel> m=new ArrayList<>();
        DefaultTableModel model=(DefaultTableModel) tblbill.getModel();
        for (int i = 0; i < tblbill.getRowCount(); i++) {
            ResultSet set;
            
            try {
                set = new MedicinController().getMedicinDetails(model.getValueAt(i, 0).toString());
                while(set.next()){
                     m.add(new MedicinModel(set.getString(1), set.getString(2), set.getString(3), set.getString(4),
                           Double.parseDouble(set.getString(5)), model.getValueAt(i, 1).toString())); 
                }  
                                 
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SetBillView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SetBillView.class.getName()).log(Level.SEVERE, null, ex);
            }
         
        }
        SetBillModel orderdetails=new SetBillModel(txtOrderId.getText(), m);
        
         try {
             SetBillController c=new SetBillController();
             c.AddOrder(order);
             c.AddOrderDetail(orderdetails);
             c.AddBill(sell);
                     
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(SetBillView.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(SetBillView.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        HomePage h=new HomePage();
        h.setVisible(true);
        this.setVisible(false);
        h.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBillActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        HomePage h=new HomePage();
        h.setVisible(true);
        this.setVisible(false);
        h.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyTyped
    
       
    }//GEN-LAST:event_jComboBox1KeyTyped

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
       
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
         MedicinController m=null;
        try {
            m = new MedicinController();
            ResultSet set=m.searchMedicin(txtSearch.getText());
              jComboBox1.removeAllItems();
            while(set.next()){
              jComboBox1.addItem(set.getString(1));
            }
             
        } catch (Exception ex) {
            Logger.getLogger(SetBillView.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_txtSearchKeyPressed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
       try{ 
           txtSearch.setText(jComboBox1.getSelectedItem().toString());
       }catch(Exception e){
           
       }
        jComboBox1.removeAllItems();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel model=(DefaultTableModel) tblbill.getModel();
        double m=0;
        
        try {
            m= new MedicinController().getPrice(txtSearch.getText());
            if(m==0){
                JOptionPane.showMessageDialog(null," Medecine Doesn't exisit try again");
                return;
            }
            m*=Double.parseDouble(txtQuantity.getText());
            sum+=m;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SetBillView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SetBillView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        Object [] r={txtSearch.getText(),txtQuantity.getText(),m};
        int x=IsAdded(r);
        if(x>=0){
           int c=Integer.parseInt(txtQuantity.getText());
           c+=Integer.parseInt(model.getValueAt(x, 1).toString());
           model.setValueAt(c,x, 1);
       }else{
       model.addRow(r);
       }
       
        txtAmount.setText(String.valueOf(sum));
        clearTableTxt();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtPationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPationIdActionPerformed
        txtOrderId.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPationIdActionPerformed

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        txtDoctorName.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        txtDoctorRegNo.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtDoctorRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorRegNoActionPerformed
        txtDoctorTel.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorRegNoActionPerformed

    private void txtDoctorTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorTelActionPerformed
        txtSearch.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorTelActionPerformed

    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
        double x=Double.parseDouble(txtPayment.getText())-Double.parseDouble(txtAmount.getText());
        txtBlance.setText(x+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetBillView().setVisible(true);
            }
        });
    
       
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateTime;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblbill;
    private javax.swing.JLabel txtAmount;
    private javax.swing.JLabel txtBlance;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtDoctorRegNo;
    private javax.swing.JTextField txtDoctorTel;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtPationId;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void clearTableTxt() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setDate() {
        DateTimeFormatter f=DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime s=LocalDateTime.now();
        DateTime.setText(f.format(s));
    }

    private int IsAdded(Object [] r) {
        DefaultTableModel model=(DefaultTableModel) tblbill.getModel();
         if(tblbill.getRowCount()>0){
           for (int i = 0; i <tblbill.getRowCount(); i++) {
           if(tblbill.getValueAt(i, 0).equals(r[0].toString())){
           return i;
          } 
        }
     }
    return -1;
   }
}