/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Veiw;

import Controller.MedicinController;
import Model.MedicinModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sasanka
 */
public class TblMedicin extends javax.swing.JFrame {

    /**
     * Creates new form TblMedicen
     */
    public TblMedicin() throws ClassNotFoundException, SQLException {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicen = new javax.swing.JTable();
        btnAddMedicen = new javax.swing.JButton();
        btnDeleteMedicin = new javax.swing.JButton();
        btnUpdateMedicin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(764, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 65, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medicin");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 70));

        btnBack.setBackground(new java.awt.Color(37, 51, 224));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        tblMedicen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicin_name", "Medicin_category", "Medicin_id", "Made_by", "Medicin_price", "Qquantity_on_hand"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMedicen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 730, 330));

        btnAddMedicen.setBackground(new java.awt.Color(37, 51, 224));
        btnAddMedicen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddMedicen.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMedicen.setText("Add Medicen");
        btnAddMedicen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddMedicen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 150, 30));

        btnDeleteMedicin.setBackground(new java.awt.Color(37, 51, 224));
        btnDeleteMedicin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteMedicin.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteMedicin.setText("Delete Medicin");
        btnDeleteMedicin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMedicinActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteMedicin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 170, 30));

        btnUpdateMedicin.setBackground(new java.awt.Color(37, 51, 224));
        btnUpdateMedicin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdateMedicin.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateMedicin.setText("Update Medicin");
        btnUpdateMedicin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMedicinActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateMedicin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HomePage h=new HomePage();
        h.setVisible(true);
       
         this.setVisible(false);
          h.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddMedicenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicenActionPerformed
        AddMedicin m=new AddMedicin();
        m.setVisible(true);
        m.setDefaultCloseOperation(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMedicenActionPerformed

    private void btnDeleteMedicinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedicinActionPerformed
        int row=tblMedicen.getSelectedRow();
         DefaultTableModel m=(DefaultTableModel) tblMedicen.getModel();
        try {
            MedicinController c=new MedicinController();
            if (c.deleteMedicin(tblMedicen.getValueAt(row, 2).toString())) {
                JOptionPane.showMessageDialog(null,"Delete Success");
                m.removeRow(row);
               
            }else{
                 JOptionPane.showMessageDialog(null,"Fail");
            }
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TblMedicin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TblMedicin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteMedicinActionPerformed

    private void btnUpdateMedicinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedicinActionPerformed
        int row=tblMedicen.getSelectedRow();
        DefaultTableModel m=(DefaultTableModel) tblMedicen.getModel();   
        String mName=tblMedicen.getValueAt(row, 0).toString();
        String mCategory=tblMedicen.getValueAt(row, 1).toString();
        String mId=tblMedicen.getValueAt(row, 2).toString();
        String mMadeBy=tblMedicen.getValueAt(row, 3).toString();
        String mPrice=tblMedicen.getValueAt(row, 4).toString();
        String mQtyOnHand=tblMedicen.getValueAt(row, 5).toString();
        
        MedicinModel k=new MedicinModel(mName, mCategory, mId, mMadeBy, Double.parseDouble(mPrice), mQtyOnHand);
        AddMedicin c=new AddMedicin();
        c.init(k);
        this.setVisible(false);
        c.setVisible(true);
        c.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMedicinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TblMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TblMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TblMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TblMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TblMedicin().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TblMedicin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(TblMedicin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicen;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteMedicin;
    private javax.swing.JButton btnUpdateMedicin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMedicen;
    // End of variables declaration//GEN-END:variables

    public void updateTable() throws ClassNotFoundException, SQLException {
        ResultSet set=new MedicinController().getMedicins();
        DefaultTableModel model=(DefaultTableModel)tblMedicen.getModel();
        tblMedicen.removeAll();
        while(set.next()){
            Object [] row={set.getString(1),set.getString(2),set.getString(3),
                set.getString(4),set.getString(5),set.getString(6)};
            model.addRow(row);
        }
    }
}
