/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Veiw;

import Controller.CustomerController;
import Controller.SuplierController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sasanka
 */
public class TblSuplier extends javax.swing.JFrame {

    /**
     * Creates new form TblSuplier
     */
    public TblSuplier() throws SQLException {
        initComponents();
       
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuplier = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAddSuplier = new javax.swing.JButton();
        btnDeleteSuplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(764, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 65, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Suplier");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 70));

        tblSuplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "suplier_name", "suplier_id", "suplier_address", "suplier_tel", "suplier_company"
            }
        ));
        jScrollPane1.setViewportView(tblSuplier);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 730, 320));

        btnBack.setBackground(new java.awt.Color(37, 51, 224));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        btnAddSuplier.setBackground(new java.awt.Color(37, 51, 224));
        btnAddSuplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddSuplier.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSuplier.setText("Add Suplier");
        btnAddSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSuplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 130, 30));

        btnDeleteSuplier.setBackground(new java.awt.Color(37, 51, 224));
        btnDeleteSuplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteSuplier.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteSuplier.setText("Delete Suplier");
        btnDeleteSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSuplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HomePage h=new HomePage();
        h.setVisible(true);
       
        this.setVisible(false);
         h.setDefaultCloseOperation(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSuplierActionPerformed
        AddSuplier s=new AddSuplier();
        s.setVisible(true);
        this.setVisible(false);
        s.setDefaultCloseOperation(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSuplierActionPerformed

    private void btnDeleteSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSuplierActionPerformed
         int row=tblSuplier.getSelectedRow();
        DefaultTableModel m=(DefaultTableModel) tblSuplier.getModel();
       
        try {
            CustomerController c=new CustomerController();
           if(c.deleteCustomer(tblSuplier.getValueAt(row, 1).toString())){
              JOptionPane.showMessageDialog(null,"Success");
               
               updateTable();
          }else{
                JOptionPane.showMessageDialog(null,"Fail");
           }
            
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(TblCustomer.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(TblCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteSuplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TblSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TblSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TblSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TblSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TblSuplier().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TblSuplier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSuplier;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteSuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSuplier;
    // End of variables declaration//GEN-END:variables

    public void updateTable() throws SQLException {
        ResultSet set=new SuplierController().supliers();
        DefaultTableModel model=(DefaultTableModel)tblSuplier.getModel();
        tblSuplier.removeAll();
        while(set.next()){
            Object [] row={set.getString(1),set.getString(2),set.getString(3),
                set.getString(4),set.getString(5)};
            model.addRow(row);
        }
    }
}
